- name: checkout sample patients
  tags: [patients, load_patients]
  sudo_user: "{{username}}"
  git: repo={{sample_patients_repo}}
       version={{sample_patients_branch}}
       dest={{install_dir}}/sample-patients
       update={{update_repositories}}
  register: sample_patients_checkout

- name: build sample patients
  tags: [patients]
  sudo_user: "{{username}}"
  shell: chdir={{install_dir}}/sample-patients/bin
         python generate.py --write-fhir ../generated-data {{sample_patients_generator_params}} 

- name: list sample patients
  tags: [patients, load_patients]
  shell: ls {{install_dir}}/sample-patients/generated-data/*.xml | head -n {{sample_patients_limit}}
  register: sample_patient_files

- name: load sample patients
  tags: [patients, load_patients]
  when: 
    ((sof_checkout.changed or sample_patients_checkout.changed) or force_rebuild)
    and (not fhir_server_preserve_db)
  shell: "chdir={{install_dir}}/sample-patients/generated-data/
         curl
           -u {{fhir_server_client}}:{{fhir_server_password}}
           'http://localhost:3000/?'
           -H 'Content-Type: text/xml' 
           --data-binary @{{item}}"
  with_items: sample_patient_files.stdout_lines

- name: list custom patients (json)
  tags: [patients, load_patients]
  shell: ls {{install_dir}}/sample-patients/custom-data/*.json
  register: custom_patient_files_json

- name: load custom patients (json)
  tags: [patients, load_patients]
  when: 
    ((sof_checkout.changed or sample_patients_checkout.changed) or force_rebuild)
    and (not fhir_server_preserve_db)
    and include_custom_patients
  shell: "chdir={{install_dir}}/sample-patients/custom-data/
         curl
           -u {{fhir_server_client}}:{{fhir_server_password}}
           'http://localhost:3000/?'
           -H 'Content-Type: application/json' 
           --data-binary @{{item}}"
  with_items: custom_patient_files_json.stdout_lines

#- name: list custom patients (xml)
#  tags: [patients, load_patients]
#  shell: ls {{install_dir}}/sample-patients/custom-data/*.xml
#  register: custom_patient_files_xml

#- name: load custom patients (xml)
#  tags: [patients, load_patients]
#  when: 
#    ((sof_checkout.changed or sample_patients_checkout.changed) or force_rebuild)
#    and (not fhir_server_preserve_db)
#    and include_custom_patients
#  shell: "chdir={{install_dir}}/sample-patients/custom-data/
#         curl
#           -u {{fhir_server_client}}:{{fhir_server_password}}
#           'http://localhost:3000/?'
#           -H 'Content-Type: text/xml' 
#           --data-binary @{{item}}"
#  with_items: custom_patient_files_xml.stdout_lines

#- name: checkout sample apps
#  tags: [apps]
#  sudo_user: "{{username}}"
#  git: repo={{app_server_repo}}
#       version={{app_server_branch}}
#       dest={{install_dir}}/apps
#       update={{update_repositories}}
#  register: apps_checkout

#- name: configure sample apps server
#  tags: [apps]
#  sudo_user: "{{username}}"
#  shell: sed -i -e 's/http:\/\/localhost:9080/{{ fhir_server_base | regex_replace('/', '\\/') }}/' {{install_dir}}/apps/static/fhirStarter/services.js

- name: checkout fhir starter
  tags: [apps]
  sudo_user: "{{username}}"
  git: repo={{fhir_starter_repo}}
       version={{fhir_starter_branch}}
       dest={{install_dir}}/apps/static
       update={{update_repositories}}

- name: configure sample apps server (services.js)
  tags: [apps]
  sudo_user: "{{username}}"
  template: src="config/services.js.j2"
            dest="{{install_dir}}/apps/static/fhirStarter/services.js"
            owner="{{username}}" group="{{username}}" mode=0644
            
- name: configure sample apps server (apps.json)
  tags: [apps]
  sudo_user: "{{username}}"
  template: src="config/apps.json.j2"
            dest="{{install_dir}}/apps/static/fhirStarter/apps.json"
            owner="{{username}}" group="{{username}}" mode=0644

- name: checkout cardiac risk app
  tags: [apps]
  sudo_user: "{{username}}"
  git: repo={{cardiac_risk_repo}}
       version={{cardiac_risk_branch}}
       dest={{install_dir}}/apps/static/apps/cardiac-risk
       update={{update_repositories}}
       
- name: checkout bp centiles app
  tags: [apps]
  sudo_user: "{{username}}"
  git: repo={{bp_centiles_repo}}
       version={{bp_centiles_branch}}
       dest={{install_dir}}/apps/static/apps/bp-centiles
       update={{update_repositories}}

- name: checkout growth chart app
  tags: [apps]
  sudo_user: "{{username}}"
  git: repo={{growth_chart_repo}}
       version={{growth_chart_branch}}
       dest={{install_dir}}/apps/static/apps/growth-chart
       update={{update_repositories}}

- name: checkout fhir demo app
  tags: [apps]
  sudo_user: "{{username}}"
  git: repo={{fhir_demo_app_repo}}
       version={{fhir_demo_app_branch}}
       dest={{install_dir}}/apps/static/apps/fhir-demo
       update={{update_repositories}}
       
- name: configure sample apps
  tags: [apps]
  sudo_user: "{{username}}"
  shell: sed -i -e 's/node_modules\/fhirclient\/fhir-client\.js/\.\.\/\.\.\/js\/fhir-client\.js/' {{install_dir}}/apps/static/apps/{{item}}
  with_items:
        - bp-centiles/index.html
        - bp-centiles/launch.html
        - cardiac-risk/index.html
        - cardiac-risk/launch.html
        - growth-chart/index.html
        - growth-chart/launch.html
        - fhir-demo/app/index.html
        - fhir-demo/app/launch.html
 
- name: configure nginx (sample apps)
  tags: [apps,nginx]
  template: src=nginx_apps.j2 dest=/etc/nginx/sites-enabled/apps owner=root group=root mode=0644
  notify:
        - restart nginx

- name: list sample apps
  tags: [apps, load_apps]
  shell: cat {{install_dir}}/apps/static/fhirStarter/apps.json
  register: sample_apps

- name: copy load-app script
  tags: [apps, load_apps]
  copy: src=load_sample_app.py dest={{install_dir}} mode=700
 
- name: load sample apps
  tags: [apps, load_apps]
  shell: chdir={{install_dir}}
     ./load_sample_app.py
         '{{lookup('template', '../templates/load_app.j2')}}'
         '{{auth_server_base}}'
         '{{auth_server_client}}'
         '{{auth_server_password}}'
  with_flattened: 
    - "{{ sample_apps.stdout | to_json }}"

- name: generate self-signed ssl certificate (apps server)
  tags: [apps]
  when: app_server_secure_http and not use_custom_ssl_certificates
  shell: creates=/etc/nginx/ssl/apps.crt
         /bin/echo -e "{{app_server_ssl_country}}\n{{app_server_ssl_province}}\n{{app_server_ssl_locality}}\n{{app_server_ssl_organization}}\n{{app_server_ssl_division}}\n{{app_server_host}}\n{{app_server_ssl_email}}\n" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/apps.key -out /etc/nginx/ssl/apps.crt

- name: configure nginx (sample apps)
  tags: [apps,nginx]
  template: src=nginx_apps.j2 dest=/etc/nginx/sites-enabled/apps owner=root group=root mode=0644
  notify:
        - restart nginx

- meta: flush_handlers
